run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
